# Generated by Django 4.1.4 on 2022-12-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Scheduler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="address",
            field=models.CharField(blank=True, max_length=100, verbose_name="address"),
        ),
        migrations.AddField(
            model_name="appuser",
            name="city",
            field=models.CharField(blank=True, max_length=50, verbose_name="city"),
        ),
        migrations.AddField(
            model_name="appuser",
            name="state",
            field=models.CharField(blank=True, max_length=2, verbose_name="state"),
        ),
        migrations.AddField(
            model_name="appuser",
            name="zip_code",
            field=models.CharField(blank=True, max_length=5, verbose_name="zip code"),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="pID",
            field=models.CharField(
                max_length=9,
                primary_key=True,
                serialize=False,
                verbose_name="panther ID",
            ),
        ),
    ]
