# Generated by Django 4.1.4 on 2022-12-07 04:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Scheduler", "0003_alter_appuser_options_remove_appuser_courses_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appuser",
            options={},
        ),
        migrations.AddField(
            model_name="appuser",
            name="courses",
            field=models.ManyToManyField(
                related_name="users",
                through="Scheduler.UserCourse",
                to="Scheduler.course",
            ),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
